export const audioMap = {
  "Welcome to Number Bonds for Subtraction!": "/assets/audio/audio_welcome_to_number_bonds_for_subtraction__0.mp3",
  "Today, we're going to learn how to take away numbers using number bonds.": "/assets/audio/audio_today__we_re_going_to_learn_how_to_take_away_numbe_1.mp3",
  "What happens when we take a big number and break it into two smaller parts? Can we use one part to find the missing piece?": "/assets/audio/audio_what_happens_when_we_take_a_big_number_and_break_i_2.mp3",
  "Are you ready to crack the number bonds and solve some fun subtraction challenges? Let's get started on our learning journey!": "/assets/audio/audio_are_you_ready_to_crack_the_number_bonds_and_solve__3.mp3",
  "Let's Discover!": "/assets/audio/audio_let_s_discover__4.mp3",
  "Wei Ming has 8 shiny stickers. He wants to share them with his friend Priya, so he gives 3 stickers to her. Wei Ming wonders...": "/assets/audio/audio_wei_ming_has_8_shiny_stickers__he_wants_to_share_t_5.mp3",
  "How many stickers do I have left?": "/assets/audio/audio_how_many_stickers_do_i_have_left__6.mp3",
  "Let's help Wei Ming!": "/assets/audio/audio_let_s_help_wei_ming__7.mp3",
  "To find out, we take away the 3 stickers he gave to Priya. Taking away is called subtraction. When we subtract, the number gets smaller!": "/assets/audio/audio_to_find_out__we_take_away_the_3_stickers_he_gave_t_8.mp3",
  "8 take away 3 leaves 5!": "/assets/audio/audio_8_take_away_3_leaves_5__9.mp3",
  "Subtract means take away!": "/assets/audio/audio_subtract_means_take_away__10.mp3",
  "Wei Ming drew a special picture called a number bond. He put the whole 8 at the top. Then he made two branches for the parts: 3 for Priya, and 5 for him. \"The whole minus a part equals the other part!\" he said.": "/assets/audio/audio_wei_ming_drew_a_special_picture_called_a_number_bo_11.mp3",
  "Whole minus Part equals Part!": "/assets/audio/audio_whole_minus_part_equals_part__12.mp3",
  "Crack the number bond!": "/assets/audio/audio_crack_the_number_bond__13.mp3",
  "Wei Ming was so excited! He learned he could use number bonds to solve subtraction word problems easily. \"Can we practice more?\" he asked.": "/assets/audio/audio_wei_ming_was_so_excited__he_learned_he_could_use_n_14.mp3",
  "Number bonds — here we come!": "/assets/audio/audio_number_bonds___here_we_come__15.mp3",
  "Your turn now!": "/assets/audio/audio_your_turn_now__16.mp3",
  "Find the missing number to complete the bond!": "/assets/audio/audio_find_the_missing_number_to_complete_the_bond__17.mp3",
  "Fill in the blank! Use the number pad.": "/assets/audio/audio_fill_in_the_blank__use_the_number_pad__18.mp3",
  "What did you learn?": "/assets/audio/audio_what_did_you_learn__19.mp3",
  "How confident do you feel about subtraction using number bonds?": "/assets/audio/audio_how_confident_do_you_feel_about_subtraction_using__20.mp3",
  "If I have 9 cookies and eat 4... what's left?": "/assets/audio/audio_if_i_have_9_cookies_and_eat_4____what_s_left__21.mp3",
  "What if there's a magic way to find the missing part?": "/assets/audio/audio_what_if_there_s_a_magic_way_to_find_the_missing_pa_22.mp3",
  "If there are 12 birds and 5 fly away, how many stay?": "/assets/audio/audio_if_there_are_12_birds_and_5_fly_away__how_many_sta_23.mp3",
  "Taking away is like a puzzle — we just need to find the missing piece!": "/assets/audio/audio_taking_away_is_like_a_puzzle___we_just_need_to_fin_24.mp3",
  "How can a number bond help us when we take things away?": "/assets/audio/audio_how_can_a_number_bond_help_us_when_we_take_things__25.mp3",
  "Number bonds are like secret maps for numbers!": "/assets/audio/audio_number_bonds_are_like_secret_maps_for_numbers__26.mp3",
  "If we know the whole and one part, can we find the other part?": "/assets/audio/audio_if_we_know_the_whole_and_one_part__can_we_find_the_27.mp3",
  "Subtraction is just finding the missing part of the team!": "/assets/audio/audio_subtraction_is_just_finding_the_missing_part_of_th_28.mp3",
  "What happens when we take a big number and break it into two smaller parts?": "/assets/audio/audio_what_happens_when_we_take_a_big_number_and_break_i_29.mp3",
  "That's exactly what a number bond does!": "/assets/audio/audio_that_s_exactly_what_a_number_bond_does__30.mp3"
};
